### ISSUE TITLE
User story, acceptance criteria and testing scenarios - User login functionality

### ISSUE THREAD

**Issue by ethernal12** [urosjarc/db-analyser#2]
# Overview
- This issue aims to outline and discuss the implementation of user login functionality of the application. This functionality is crucial for enabling users to access, interact with a specific database, and also to provide better user experiance and intuitive interaction with the login process.

# Job Story

- As a user, I want to be able to log into the application** so that I can interact, explore, and navigate within a specific database.

# Pre-conditions:

- **User must provide database URL.**

# User Flow:

## 1. Navigating to Database Connection:

-  User clicks on the DB tab in the vertical left-side navigation bar.

## 2. Entering Database Information:

-   In the first input bar, the user enters a random name to describe the database (non-restrictive).
-   In the second input bar, the user enters the database URL.
-   From a dropdown menu, the user selects the database management system (DBMS) that matches their database type.

## 3. Initiating the Connection:

- The user clicks the ‘Login’ button to initiate the connection.

## 4.  Feedback:

- **Upon successful login**, the user receives a confirmation message in the right side logs, with the messages as:
    - DB connected :< DBMS >| <DATABASE NAME> → DATABASE
    - Client connected active!
- **If the login fails** (due to incorrect URL format, or connection issues), the user is presented with a descriptive error log message.

# Post conditions:
-  None

# Scenarios:
## 1. Scenario: Successful Application Login

- **Given** that the user is on the Db Connection input form.
- **When** the user enters a valid database name and URL.
- **And** selects a supported DBMS type from the dropdown.
- **And** clicks the login button.
- **Then** the system validates the database URL.
- **And** the user is successfully logged into the application.
- **And** receives a confirmation message about the successful connection in the left-side logs area.

## 2. Scenario: Login Failure Due to Incorrect Database Details

- **Given** that the user is on the Db Connection input form.
- **When** the user enters a database file instead of database URL.
- **And** selects a supported DBMS type from the dropdown.
- **And** clicks the login button.
- **Then** the system validates the database URL.
- **And** the login attempt fails.
- **And** the user receives an error message with the reason for the failure in the left-side logs area.

**Comment by urosjarc** [comment]
@ethernal12 Naj bodo user stories kar v posebnem dokumentu ločeni od github issuetov in bodo user stories vse skupaj na eni lokaciji, na github issues pa naj bodo samo issueti v primeru če funkcijonalnost ne ustreza tisti ki je napisana v dokumentu.

Ta issue bom pa closal.

**Comment by ethernal12** [comment]
Ok...bom delal naprej user story in si delal zapiske, potem se pa naprimer
dobiva jutri zvečer in pogovoriva, kako naj bo vse organizirano.

V V sob., 30. mar. 2024 ob 06:08 je oseba Uroš Jarc <
***@***.***> napisala:
